const axios = require('axios');
const pool = require('../config/database');

// American Whitewater API endpoint
const AW_API_BASE = 'https://www.americanwhitewater.org/content/River/view/river-detail';

/**
 * Top 100 Whitewater Rapids in North America
 * Data compiled from American Whitewater, paddling guidebooks, and community knowledge
 */
async function seedSampleData() {
  console.log('🌊 Seeding top 100 whitewater rapids...');

  const sampleRapids = [
    // Grand Canyon - Colorado River
    {
      name: 'Lava Falls',
      river: 'Colorado River',
      description: 'Legendary Class V (or X at high water) rapid in the Grand Canyon. One of the most famous rapids in North America.',
      latitude: 36.2128,
      longitude: -113.1222,
      difficulty: 'V',
      length_miles: 0.15,
      gradient_fppm: 37,
      optimal_flow_min: 10000,
      optimal_flow_max: 25000,
      season: 'April-September',
      hazards: ['Massive waves', 'Powerful holes', 'Rock garden'],
      access_notes: 'Grand Canyon permit required. Multi-day trip necessary.',
      permit_required: true,
    },
    {
      name: 'Crystal Rapid',
      river: 'Colorado River',
      description: 'Notorious Grand Canyon rapid. Created by a flash flood in 1966, it features the massive Crystal Hole.',
      latitude: 36.1147,
      longitude: -112.3428,
      difficulty: 'IV-V',
      length_miles: 0.1,
      gradient_fppm: 15,
      optimal_flow_min: 10000,
      optimal_flow_max: 20000,
      season: 'April-September',
      hazards: ['Crystal Hole', 'Rock garden', 'Powerful waves'],
      access_notes: 'Grand Canyon permit required. Mile 98.',
      permit_required: true,
    },
    {
      name: 'Hermit Rapid',
      river: 'Colorado River',
      description: 'Technical Class IV-V rapid with large waves and holes. One of the biggest in the Grand Canyon.',
      latitude: 36.0858,
      longitude: -112.2525,
      difficulty: 'IV-V',
      length_miles: 0.2,
      gradient_fppm: 18,
      optimal_flow_min: 10000,
      optimal_flow_max: 25000,
      season: 'April-September',
      hazards: ['Large waves', 'Multiple holes', 'Rock garden'],
      access_notes: 'Grand Canyon permit required. Mile 95.',
      permit_required: true,
    },
    {
      name: 'Horn Creek Rapid',
      river: 'Colorado River',
      description: 'Sharp technical rapid requiring precise navigation through rocky channels.',
      latitude: 36.0967,
      longitude: -112.0878,
      difficulty: 'IV',
      length_miles: 0.1,
      gradient_fppm: 20,
      optimal_flow_min: 8000,
      optimal_flow_max: 20000,
      season: 'April-September',
      hazards: ['Rocks', 'Narrow channels', 'Powerful hydraulics'],
      access_notes: 'Grand Canyon permit required. Mile 90.',
      permit_required: true,
    },
    {
      name: 'Hance Rapid',
      river: 'Colorado River',
      description: 'Long, technical Class IV boulder garden requiring multiple moves.',
      latitude: 36.0706,
      longitude: -111.9197,
      difficulty: 'IV',
      length_miles: 0.25,
      gradient_fppm: 30,
      optimal_flow_min: 8000,
      optimal_flow_max: 20000,
      season: 'April-September',
      hazards: ['Boulder maze', 'Continuous technical moves', 'Multiple holes'],
      access_notes: 'Grand Canyon permit required. Mile 77.',
      permit_required: true,
    },

    // West Virginia - Gauley River
    {
      name: 'Pillow Rock',
      river: 'Gauley River',
      description: 'The most famous rapid on the Gauley. A huge undercut rock in the center creates multiple routes.',
      latitude: 38.1728,
      longitude: -80.9744,
      difficulty: 'V',
      length_miles: 0.1,
      gradient_fppm: 28,
      optimal_flow_min: 1200,
      optimal_flow_max: 3500,
      season: 'September-October (dam releases)',
      hazards: ['Undercut pillow rock', 'Powerful holes', 'Reversal'],
      access_notes: 'Upper Gauley section. Summersville Dam releases.',
      permit_required: false,
    },
    {
      name: 'Lost Paddle',
      river: 'Gauley River',
      description: 'Technical Class V rapid with the notorious Room of Doom hole.',
      latitude: 38.1656,
      longitude: -80.9692,
      difficulty: 'V',
      length_miles: 0.15,
      gradient_fppm: 26,
      optimal_flow_min: 1200,
      optimal_flow_max: 3500,
      season: 'September-October',
      hazards: ['Room of Doom', 'Undercuts', 'Powerful hydraulics'],
      access_notes: 'Upper Gauley. Scout from river left.',
      permit_required: false,
    },
    {
      name: 'Sweet\'s Falls',
      river: 'Gauley River',
      description: 'Steep Class V waterfall drop with a powerful hole at the bottom.',
      latitude: 38.1589,
      longitude: -80.9633,
      difficulty: 'V',
      length_miles: 0.05,
      gradient_fppm: 50,
      optimal_flow_min: 1200,
      optimal_flow_max: 3000,
      season: 'September-October',
      hazards: ['Falls', 'Sticky hole', 'Undercut rocks'],
      access_notes: 'Upper Gauley. Portage option on left.',
      permit_required: false,
    },
    {
      name: 'Iron Ring',
      river: 'Gauley River',
      description: 'Long Class IV rapid with continuous waves and holes.',
      latitude: 38.1511,
      longitude: -80.9567,
      difficulty: 'IV',
      length_miles: 0.2,
      gradient_fppm: 24,
      optimal_flow_min: 1500,
      optimal_flow_max: 4000,
      season: 'September-October',
      hazards: ['Continuous waves', 'Multiple holes', 'Strong current'],
      access_notes: 'Upper Gauley section.',
      permit_required: false,
    },

    // West Virginia - New River
    {
      name: 'Double Z',
      river: 'New River',
      description: 'Technical Class IV rapid with tight S-turns through large boulders.',
      latitude: 37.9733,
      longitude: -81.0806,
      difficulty: 'IV',
      length_miles: 0.15,
      gradient_fppm: 15,
      optimal_flow_min: 1500,
      optimal_flow_max: 8000,
      season: 'Year-round',
      hazards: ['Tight turns', 'Boulders', 'Holes'],
      access_notes: 'Lower New River Gorge. Highway 19 access.',
      permit_required: false,
    },
    {
      name: 'Upper Railroad',
      river: 'New River',
      description: 'Big wave train with powerful hydraulics at higher flows.',
      latitude: 37.9789,
      longitude: -81.0733,
      difficulty: 'III-IV',
      length_miles: 0.1,
      gradient_fppm: 12,
      optimal_flow_min: 2000,
      optimal_flow_max: 10000,
      season: 'Year-round',
      hazards: ['Large waves', 'Holes', 'Undercuts on left'],
      access_notes: 'Lower New River Gorge.',
      permit_required: false,
    },

    // Idaho - Payette River System
    {
      name: 'Jacob\'s Ladder',
      river: 'Payette River (South Fork)',
      description: 'Technical Class IV+ staircase rapid. Multiple ledges requiring precise lines.',
      latitude: 44.1889,
      longitude: -115.5628,
      difficulty: 'IV+',
      length_miles: 0.2,
      gradient_fppm: 100,
      optimal_flow_min: 2000,
      optimal_flow_max: 5000,
      season: 'May-June',
      hazards: ['Stacked ledges', 'Holes', 'Tight channels'],
      access_notes: 'Highway 21 access. Staircase section.',
      permit_required: false,
    },
    {
      name: 'Carnage Corner',
      river: 'Payette River (North Fork)',
      description: 'Challenging Class IV+ rapid with tight technical moves and powerful hydraulics.',
      latitude: 44.7367,
      longitude: -115.9556,
      difficulty: 'IV+',
      length_miles: 0.1,
      gradient_fppm: 110,
      optimal_flow_min: 800,
      optimal_flow_max: 2500,
      season: 'June-July',
      hazards: ['Powerful hole', 'Sieves', 'Undercuts'],
      access_notes: 'Banks-Lowman Road provides access. Popular commercial section.',
      permit_required: false,
    },
    {
      name: 'Golf Course',
      river: 'Payette River (North Fork)',
      description: 'Class IV rapid with multiple channels through boulder garden.',
      latitude: 44.7289,
      longitude: -115.9478,
      difficulty: 'IV',
      length_miles: 0.15,
      gradient_fppm: 95,
      optimal_flow_min: 800,
      optimal_flow_max: 2500,
      season: 'June-July',
      hazards: ['Boulders', 'Multiple channels', 'Holes'],
      access_notes: 'North Fork Payette.',
      permit_required: false,
    },
    {
      name: 'Juicer',
      river: 'Payette River (North Fork)',
      description: 'Technical Class IV+ drop with powerful hydraulics.',
      latitude: 44.7423,
      longitude: -115.9611,
      difficulty: 'IV+',
      length_miles: 0.08,
      gradient_fppm: 120,
      optimal_flow_min: 800,
      optimal_flow_max: 2000,
      season: 'June-July',
      hazards: ['Large drop', 'Sticky hole', 'Rocks'],
      access_notes: 'North Fork Payette.',
      permit_required: false,
    },
    {
      name: 'Cabarton',
      river: 'Payette River (North Fork)',
      description: 'Long Class IV rapid with continuous action and big waves.',
      latitude: 44.7511,
      longitude: -115.9689,
      difficulty: 'IV',
      length_miles: 0.2,
      gradient_fppm: 85,
      optimal_flow_min: 1000,
      optimal_flow_max: 2500,
      season: 'June-July',
      hazards: ['Big waves', 'Holes', 'Boulders'],
      access_notes: 'North Fork Payette.',
      permit_required: false,
    },

    // Idaho - Middle Fork Salmon
    {
      name: 'Velvet Falls',
      river: 'Middle Fork Salmon River',
      description: 'Class IV waterfall drop, one of the biggest on the Middle Fork.',
      latitude: 44.7856,
      longitude: -115.1289,
      difficulty: 'IV',
      length_miles: 0.05,
      gradient_fppm: 60,
      optimal_flow_min: 1500,
      optimal_flow_max: 4000,
      season: 'June-August',
      hazards: ['Falls', 'Hole', 'Rocks'],
      access_notes: 'Middle Fork permit required. Multi-day trip.',
      permit_required: true,
    },
    {
      name: 'Tappan Falls',
      river: 'Middle Fork Salmon River',
      description: 'Technical Class IV falls requiring precise line.',
      latitude: 44.8123,
      longitude: -115.0978,
      difficulty: 'IV',
      length_miles: 0.05,
      gradient_fppm: 55,
      optimal_flow_min: 1500,
      optimal_flow_max: 4000,
      season: 'June-August',
      hazards: ['Falls', 'Rocks', 'Hydraulics'],
      access_notes: 'Middle Fork permit required.',
      permit_required: true,
    },
    {
      name: 'Redside',
      river: 'Middle Fork Salmon River',
      description: 'Complex Class IV rapid with multiple routes through rock garden.',
      latitude: 44.8567,
      longitude: -115.0456,
      difficulty: 'IV',
      length_miles: 0.15,
      gradient_fppm: 30,
      optimal_flow_min: 1500,
      optimal_flow_max: 5000,
      season: 'June-August',
      hazards: ['Boulders', 'Multiple channels', 'Holes'],
      access_notes: 'Middle Fork permit required.',
      permit_required: true,
    },

    // Idaho - Lochsa River
    {
      name: 'Lochsa Falls',
      river: 'Lochsa River',
      description: 'A technical Class IV rapid with a significant drop. Scout carefully on river left.',
      latitude: 46.4583,
      longitude: -115.6389,
      difficulty: 'IV',
      length_miles: 0.2,
      gradient_fppm: 80,
      optimal_flow_min: 1500,
      optimal_flow_max: 4000,
      season: 'May-June',
      hazards: ['Large rocks', 'Strong hydraulics', 'Undercut ledge on right'],
      access_notes: 'Highway 12 parallels the river. Multiple pull-outs available.',
      permit_required: false,
    },

    // California - Tuolumne River
    {
      name: 'Clavey Falls',
      river: 'Tuolumne River',
      description: 'Iconic Class V rapid. A series of large drops culminating in the main falls.',
      latitude: 37.9167,
      longitude: -120.2167,
      difficulty: 'V',
      length_miles: 0.15,
      gradient_fppm: 120,
      optimal_flow_min: 1800,
      optimal_flow_max: 6000,
      season: 'April-July',
      hazards: ['Large drops', 'Powerful hydraulics', 'Rock sieves'],
      access_notes: 'Multi-day trip from Meral\'s Pool or Cherry Creek.',
      permit_required: true,
    },
    {
      name: 'Pinball',
      river: 'Tuolumne River',
      description: 'Technical Class IV boulder garden requiring quick moves.',
      latitude: 37.9233,
      longitude: -120.2089,
      difficulty: 'IV',
      length_miles: 0.1,
      gradient_fppm: 90,
      optimal_flow_min: 2000,
      optimal_flow_max: 6000,
      season: 'April-July',
      hazards: ['Boulders', 'Tight channels', 'Holes'],
      access_notes: 'Tuolumne River.',
      permit_required: true,
    },
    {
      name: 'Hell\'s Kitchen',
      river: 'Tuolumne River',
      description: 'Long Class IV+ rapid with continuous big water.',
      latitude: 37.9311,
      longitude: -120.1967,
      difficulty: 'IV+',
      length_miles: 0.25,
      gradient_fppm: 85,
      optimal_flow_min: 2500,
      optimal_flow_max: 8000,
      season: 'April-July',
      hazards: ['Big waves', 'Holes', 'Continuous action'],
      access_notes: 'Tuolumne River.',
      permit_required: true,
    },

    // California - American River
    {
      name: 'Troublemaker',
      river: 'American River (South Fork)',
      description: 'Class III+ rapid, one of the biggest on the popular South Fork.',
      latitude: 38.7333,
      longitude: -120.8517,
      difficulty: 'III+',
      length_miles: 0.15,
      gradient_fppm: 25,
      optimal_flow_min: 1000,
      optimal_flow_max: 5000,
      season: 'April-September',
      hazards: ['Large waves', 'Holes', 'Rocks'],
      access_notes: 'Highway 49 access. Very popular commercial section.',
      permit_required: false,
    },
    {
      name: 'Satan\'s Cesspool',
      river: 'American River (South Fork)',
      description: 'Technical Class III rapid with swirling currents.',
      latitude: 38.7289,
      longitude: -120.8467,
      difficulty: 'III',
      length_miles: 0.1,
      gradient_fppm: 20,
      optimal_flow_min: 1000,
      optimal_flow_max: 5000,
      season: 'April-September',
      hazards: ['Swirling water', 'Rocks', 'Holes'],
      access_notes: 'South Fork American.',
      permit_required: false,
    },
    {
      name: 'Tunnel Chute',
      river: 'American River (North Fork)',
      description: 'Class IV+ technical slot with powerful hydraulics.',
      latitude: 39.0122,
      longitude: -120.9478,
      difficulty: 'IV+',
      length_miles: 0.08,
      gradient_fppm: 110,
      optimal_flow_min: 800,
      optimal_flow_max: 2000,
      season: 'March-June',
      hazards: ['Narrow slot', 'Powerful hole', 'High consequence'],
      access_notes: 'North Fork American. Advanced paddlers only.',
      permit_required: false,
    },

    // Colorado - Arkansas River
    {
      name: 'Pinball',
      river: 'Arkansas River',
      description: 'Fast-paced Class IV rapid in the Numbers section. Continuous boulder dodging required.',
      latitude: 38.9231,
      longitude: -106.2456,
      difficulty: 'IV',
      length_miles: 0.25,
      gradient_fppm: 90,
      optimal_flow_min: 600,
      optimal_flow_max: 1500,
      season: 'May-July',
      hazards: ['Continuous boulders', 'Narrow channels', 'Keeper holes'],
      access_notes: 'Highway 24 access. Popular commercial stretch.',
      permit_required: false,
    },
    {
      name: 'Zoom Flume',
      river: 'Arkansas River',
      description: 'Class IV rapid with big waves and holes in Brown\'s Canyon.',
      latitude: 38.6478,
      longitude: -105.9133,
      difficulty: 'IV',
      length_miles: 0.15,
      gradient_fppm: 35,
      optimal_flow_min: 1200,
      optimal_flow_max: 3500,
      season: 'May-August',
      hazards: ['Big waves', 'Holes', 'Rocks'],
      access_notes: 'Brown\'s Canyon National Monument.',
      permit_required: false,
    },
    {
      name: 'Seidel\'s Suckhole',
      river: 'Arkansas River',
      description: 'Class III+ rapid with a notorious hole at center.',
      latitude: 38.6544,
      longitude: -105.9067,
      difficulty: 'III+',
      length_miles: 0.1,
      gradient_fppm: 28,
      optimal_flow_min: 1200,
      optimal_flow_max: 3500,
      season: 'May-August',
      hazards: ['Keeper hole', 'Waves', 'Rocks'],
      access_notes: 'Brown\'s Canyon.',
      permit_required: false,
    },

    // Oregon - Deschutes River
    {
      name: 'Oak Springs',
      river: 'Deschutes River',
      description: 'Long Class IV rapid with multiple drops and large waves.',
      latitude: 45.2267,
      longitude: -121.0944,
      difficulty: 'IV',
      length_miles: 0.3,
      gradient_fppm: 40,
      optimal_flow_min: 3000,
      optimal_flow_max: 8000,
      season: 'Year-round',
      hazards: ['Big waves', 'Holes', 'Long swim'],
      access_notes: 'Lower Deschutes. Permit required for camping.',
      permit_required: false,
    },
    {
      name: 'Whitehorse Rapids',
      river: 'Deschutes River',
      description: 'Class IV rapid with large wave trains and holes.',
      latitude: 45.2133,
      longitude: -121.0811,
      difficulty: 'IV',
      length_miles: 0.2,
      gradient_fppm: 38,
      optimal_flow_min: 3000,
      optimal_flow_max: 8000,
      season: 'Year-round',
      hazards: ['Large waves', 'Holes', 'Rocks'],
      access_notes: 'Lower Deschutes.',
      permit_required: false,
    },

    // Washington - White Salmon River
    {
      name: 'Husum Falls',
      river: 'White Salmon River',
      description: 'Class V waterfall drop, one of the most run waterfalls in the world.',
      latitude: 45.7722,
      longitude: -121.4789,
      difficulty: 'V',
      length_miles: 0.03,
      gradient_fppm: 150,
      optimal_flow_min: 800,
      optimal_flow_max: 2500,
      season: 'Year-round',
      hazards: ['Waterfall', 'Cave at bottom', 'Powerful hydraulics'],
      access_notes: 'Husum. Walk-in access. Portage option.',
      permit_required: false,
    },
    {
      name: 'Sunshine Falls',
      river: 'White Salmon River',
      description: 'Beautiful Class IV ledge drop. Clean line down the center or technical river right route.',
      latitude: 45.7567,
      longitude: -121.5144,
      difficulty: 'IV',
      length_miles: 0.05,
      gradient_fppm: 75,
      optimal_flow_min: 1200,
      optimal_flow_max: 3000,
      season: 'Year-round',
      hazards: ['Ledge hole', 'Rocks at bottom', 'Recirculation'],
      access_notes: 'Husum put-in. Popular day trip destination.',
      permit_required: false,
    },

    // Southeast - Chattooga River
    {
      name: 'Big Mallard',
      river: 'Chattooga River',
      description: 'Classic southeastern Class IV rapid. Technical boulder garden requiring precise boat control.',
      latitude: 34.9267,
      longitude: -83.1533,
      difficulty: 'IV',
      length_miles: 0.15,
      gradient_fppm: 50,
      optimal_flow_min: 1.5,
      optimal_flow_max: 2.5,
      season: 'March-May, after rain',
      hazards: ['Boulder maze', 'Pinning potential', 'Recirculating holes'],
      access_notes: 'Section III put-in at Earl\'s Ford. Parking available.',
      permit_required: false,
    },
    {
      name: 'Bull Sluice',
      river: 'Chattooga River',
      description: 'Famous Class IV-V drop through a narrow chute. Very popular photo spot.',
      latitude: 34.9156,
      longitude: -83.1478,
      difficulty: 'IV-V',
      length_miles: 0.05,
      gradient_fppm: 80,
      optimal_flow_min: 1.5,
      optimal_flow_max: 2.0,
      season: 'March-May',
      hazards: ['Narrow slot', 'Undercut rocks', 'Pinning'],
      access_notes: 'Section IV. Often portaged. Scout carefully.',
      permit_required: false,
    },
    {
      name: 'Five Falls',
      river: 'Chattooga River',
      description: 'Series of five Class IV-V drops in quick succession.',
      latitude: 34.9089,
      longitude: -83.1422,
      difficulty: 'IV-V',
      length_miles: 0.15,
      gradient_fppm: 120,
      optimal_flow_min: 1.5,
      optimal_flow_max: 2.0,
      season: 'March-May',
      hazards: ['Multiple drops', 'Undercuts', 'Pinning'],
      access_notes: 'Section IV. Extremely technical.',
      permit_required: false,
    },
    {
      name: 'Woodall Shoals',
      river: 'Chattooga River',
      description: 'Class IV-V ledge with dangerous reversal. Fatalities have occurred here.',
      latitude: 34.8978,
      longitude: -83.1367,
      difficulty: 'IV-V',
      length_miles: 0.05,
      gradient_fppm: 90,
      optimal_flow_min: 1.5,
      optimal_flow_max: 2.0,
      season: 'March-May',
      hazards: ['Keeper hydraulic', 'Undercuts', 'High consequence'],
      access_notes: 'Section IV. Mandatory portage recommended.',
      permit_required: false,
    },

    // Tennessee - Ocoee River
    {
      name: 'Double Trouble',
      river: 'Ocoee River',
      description: 'Class III rapid with two successive holes. Olympic whitewater venue.',
      latitude: 35.0878,
      longitude: -84.4122,
      difficulty: 'III',
      length_miles: 0.1,
      gradient_fppm: 40,
      optimal_flow_min: 1200,
      optimal_flow_max: 2000,
      season: 'March-September (dam releases)',
      hazards: ['Two holes', 'Waves', 'Rocks'],
      access_notes: 'Middle Ocoee. Dam controlled flow.',
      permit_required: false,
    },
    {
      name: 'Broken Nose',
      river: 'Ocoee River',
      description: 'Technical Class III rapid with precise line required.',
      latitude: 35.0856,
      longitude: -84.4089,
      difficulty: 'III',
      length_miles: 0.08,
      gradient_fppm: 45,
      optimal_flow_min: 1200,
      optimal_flow_max: 2000,
      season: 'March-September',
      hazards: ['Rocks', 'Narrow channels', 'Hole'],
      access_notes: 'Middle Ocoee.',
      permit_required: false,
    },

    // North Carolina - Green River
    {
      name: 'Gorilla',
      river: 'Green River',
      description: 'Class V+ big water rapid. One of the most intense in the Southeast.',
      latitude: 35.2611,
      longitude: -82.2167,
      difficulty: 'V+',
      length_miles: 0.2,
      gradient_fppm: 150,
      optimal_flow_min: 800,
      optimal_flow_max: 2000,
      season: 'Year-round (dam releases)',
      hazards: ['Massive holes', 'Undercuts', 'High consequence'],
      access_notes: 'Green River Narrows. Expert paddlers only.',
      permit_required: false,
    },
    {
      name: 'Chief',
      river: 'Green River',
      description: 'Class V rapid with large hole and technical moves.',
      latitude: 35.2656,
      longitude: -82.2133,
      difficulty: 'V',
      length_miles: 0.1,
      gradient_fppm: 140,
      optimal_flow_min: 800,
      optimal_flow_max: 2000,
      season: 'Year-round',
      hazards: ['Big hole', 'Rocks', 'Undercuts'],
      access_notes: 'Green River Narrows.',
      permit_required: false,
    },
    {
      name: 'Zwicks',
      river: 'Green River',
      description: 'Class V rapid with tight entrance and powerful exit hole.',
      latitude: 35.2689,
      longitude: -82.2111,
      difficulty: 'V',
      length_miles: 0.08,
      gradient_fppm: 135,
      optimal_flow_min: 800,
      optimal_flow_max: 1800,
      season: 'Year-round',
      hazards: ['Narrow entrance', 'Exit hole', 'Undercuts'],
      access_notes: 'Green River Narrows.',
      permit_required: false,
    },

    // North Carolina - French Broad River
    {
      name: 'Frank Bell\'s',
      river: 'French Broad River',
      description: 'Class III ledge drop with sticky hole at certain flows.',
      latitude: 35.8222,
      longitude: -82.7333,
      difficulty: 'III',
      length_miles: 0.05,
      gradient_fppm: 15,
      optimal_flow_min: 1500,
      optimal_flow_max: 6000,
      season: 'Year-round',
      hazards: ['Ledge hole', 'Rocks', 'Swirling currents'],
      access_notes: 'Asheville section. Popular play spot.',
      permit_required: false,
    },

    // Pennsylvania - Youghiogheny River
    {
      name: 'Dimple Rock',
      river: 'Youghiogheny River',
      description: 'Class III rapid with a large undercut rock in the center.',
      latitude: 39.8544,
      longitude: -79.3733,
      difficulty: 'III',
      length_miles: 0.1,
      gradient_fppm: 18,
      optimal_flow_min: 1.8,
      optimal_flow_max: 3.5,
      season: 'March-October (dam releases)',
      hazards: ['Undercut Dimple Rock', 'Holes', 'Pin potential'],
      access_notes: 'Lower Yough. Dam controlled. Very popular.',
      permit_required: false,
    },
    {
      name: 'Railroad Rapids',
      river: 'Youghiogheny River',
      description: 'Class III rapid with big waves and holes at higher flows.',
      latitude: 39.8622,
      longitude: -79.3667,
      difficulty: 'III',
      length_miles: 0.15,
      gradient_fppm: 20,
      optimal_flow_min: 1.8,
      optimal_flow_max: 4.0,
      season: 'March-October',
      hazards: ['Large waves', 'Holes', 'Rocks'],
      access_notes: 'Lower Yough.',
      permit_required: false,
    },

    // Maryland - Savage River
    {
      name: 'Big Savage',
      river: 'Savage River',
      description: 'Class IV drop with large hole at bottom.',
      latitude: 39.5689,
      longitude: -79.1244,
      difficulty: 'IV',
      length_miles: 0.08,
      gradient_fppm: 60,
      optimal_flow_min: 400,
      optimal_flow_max: 1000,
      season: 'March-May (dam releases)',
      hazards: ['Large hole', 'Rocks', 'Undercuts'],
      access_notes: 'Upper Savage. Dam releases only.',
      permit_required: false,
    },

    // New York - Black River
    {
      name: 'Knife\'s Edge',
      river: 'Black River',
      description: 'Class IV+ rapid with precise line through narrow slot.',
      latitude: 43.7633,
      longitude: -75.4889,
      difficulty: 'IV+',
      length_miles: 0.1,
      gradient_fppm: 80,
      optimal_flow_min: 800,
      optimal_flow_max: 2000,
      season: 'April-June',
      hazards: ['Narrow slot', 'Undercuts', 'Pinning'],
      access_notes: 'Black River Canyon.',
      permit_required: false,
    },

    // Vermont - White River
    {
      name: 'Mica Dam',
      river: 'White River',
      description: 'Class IV ledge drop, one of the biggest drops in Vermont.',
      latitude: 43.7867,
      longitude: -72.4933,
      difficulty: 'IV',
      length_miles: 0.05,
      gradient_fppm: 70,
      optimal_flow_min: 600,
      optimal_flow_max: 2000,
      season: 'April-May',
      hazards: ['Ledge', 'Hole', 'Rocks'],
      access_notes: 'Upper White River.',
      permit_required: false,
    },

    // Maine - Kennebec River
    {
      name: 'Magic Falls',
      river: 'Kennebec River',
      description: 'Class IV ledge with large hole. Popular commercial rapid.',
      latitude: 45.3367,
      longitude: -69.9889,
      difficulty: 'IV',
      length_miles: 0.05,
      gradient_fppm: 40,
      optimal_flow_min: 4000,
      optimal_flow_max: 8000,
      season: 'May-September (dam releases)',
      hazards: ['Ledge hole', 'Rocks', 'Backwash'],
      access_notes: 'Lower Kennebec. Dam controlled.',
      permit_required: false,
    },

    // Washington - Skykomish River
    {
      name: 'Boulder Drop',
      river: 'Skykomish River',
      description: 'Class IV+ big water rapid with massive boulder garden.',
      latitude: 47.7011,
      longitude: -121.4244,
      difficulty: 'IV+',
      length_miles: 0.2,
      gradient_fppm: 70,
      optimal_flow_min: 3000,
      optimal_flow_max: 8000,
      season: 'October-June',
      hazards: ['Large boulders', 'Holes', 'Strong current'],
      access_notes: 'Canyon section. Highway 2 access.',
      permit_required: false,
    },

    // Montana - Gallatin River
    {
      name: 'Mad Mile',
      river: 'Gallatin River',
      description: 'Continuous Class IV section with non-stop action.',
      latitude: 45.3456,
      longitude: -111.2333,
      difficulty: 'IV',
      length_miles: 1.0,
      gradient_fppm: 60,
      optimal_flow_min: 1200,
      optimal_flow_max: 3000,
      season: 'May-July',
      hazards: ['Continuous rapids', 'Rocks', 'Holes'],
      access_notes: 'Lower Gallatin Canyon. Highway 191 access.',
      permit_required: false,
    },

    // Wyoming - Snake River
    {
      name: 'Lunch Counter',
      river: 'Snake River',
      description: 'Class III+ wave train, one of the biggest in the US.',
      latitude: 43.4922,
      longitude: -110.7667,
      difficulty: 'III+',
      length_miles: 0.2,
      gradient_fppm: 25,
      optimal_flow_min: 8000,
      optimal_flow_max: 20000,
      season: 'May-September',
      hazards: ['Huge waves', 'Holes', 'Strong current'],
      access_notes: 'Snake River Canyon. Popular commercial run.',
      permit_required: false,
    },
    {
      name: 'Big Kahuna',
      river: 'Snake River',
      description: 'Class III rapid with large wave train.',
      latitude: 43.4856,
      longitude: -110.7722,
      difficulty: 'III',
      length_miles: 0.15,
      gradient_fppm: 22,
      optimal_flow_min: 8000,
      optimal_flow_max: 20000,
      season: 'May-September',
      hazards: ['Big waves', 'Holes', 'Current'],
      access_notes: 'Snake River Canyon.',
      permit_required: false,
    },

    // Utah - Westwater Canyon (Colorado River)
    {
      name: 'Skull Rapid',
      river: 'Colorado River',
      description: 'Class IV rapid in Westwater Canyon with large holes.',
      latitude: 38.9633,
      longitude: -109.1489,
      difficulty: 'IV',
      length_miles: 0.15,
      gradient_fppm: 35,
      optimal_flow_min: 5000,
      optimal_flow_max: 20000,
      season: 'April-September',
      hazards: ['Large holes', 'Waves', 'Rocks'],
      access_notes: 'Westwater Canyon. Permit required for camping.',
      permit_required: true,
    },
    {
      name: 'Room of Doom',
      river: 'Colorado River',
      description: 'Class III-IV rapid with powerful hole at certain flows.',
      latitude: 38.9589,
      longitude: -109.1456,
      difficulty: 'III-IV',
      length_miles: 0.1,
      gradient_fppm: 30,
      optimal_flow_min: 5000,
      optimal_flow_max: 20000,
      season: 'April-September',
      hazards: ['Keeper hole', 'Waves', 'Rocks'],
      access_notes: 'Westwater Canyon.',
      permit_required: true,
    },

    // Cataract Canyon (Colorado River)
    {
      name: 'Big Drop 2',
      river: 'Colorado River',
      description: 'Class IV-V rapid with massive waves at high water. Biggest drop in Cataract Canyon.',
      latitude: 38.1911,
      longitude: -109.8967,
      difficulty: 'IV-V',
      length_miles: 0.2,
      gradient_fppm: 45,
      optimal_flow_min: 10000,
      optimal_flow_max: 50000,
      season: 'April-June',
      hazards: ['Enormous waves', 'Holes', 'Long swim'],
      access_notes: 'Cataract Canyon. Permit required. Multi-day trip.',
      permit_required: true,
    },
    {
      name: 'Big Drop 3',
      river: 'Colorado River',
      description: 'Class IV rapid with large wave train immediately after Big Drop 2.',
      latitude: 38.1889,
      longitude: -109.8944,
      difficulty: 'IV',
      length_miles: 0.15,
      gradient_fppm: 40,
      optimal_flow_min: 10000,
      optimal_flow_max: 50000,
      season: 'April-June',
      hazards: ['Big waves', 'Holes', 'Continuous action'],
      access_notes: 'Cataract Canyon.',
      permit_required: true,
    },

    // Canada - Ottawa River
    {
      name: 'Coliseum',
      river: 'Ottawa River',
      description: 'Class IV big water rapid with enormous waves and holes.',
      latitude: 45.8211,
      longitude: -76.8856,
      difficulty: 'IV',
      length_miles: 0.2,
      gradient_fppm: 25,
      optimal_flow_min: 15000,
      optimal_flow_max: 50000,
      season: 'May-June',
      hazards: ['Huge waves', 'Large holes', 'Strong current'],
      access_notes: 'Ottawa River, Ontario. Dam controlled.',
      permit_required: false,
    },
    {
      name: 'Phil\'s Hole',
      river: 'Ottawa River',
      description: 'Class III-IV rapid with large play wave and hole.',
      latitude: 45.8178,
      longitude: -76.8822,
      difficulty: 'III-IV',
      length_miles: 0.1,
      gradient_fppm: 20,
      optimal_flow_min: 15000,
      optimal_flow_max: 50000,
      season: 'May-June',
      hazards: ['Large hole', 'Waves', 'Current'],
      access_notes: 'Ottawa River.',
      permit_required: false,
    },

    // Chile - Futaleufú River (Bonus International)
    {
      name: 'Mundaca',
      river: 'Futaleufú River',
      description: 'Class V rapid with massive holes. One of the most challenging rapids in the world.',
      latitude: -43.1833,
      longitude: -71.8667,
      difficulty: 'V',
      length_miles: 0.15,
      gradient_fppm: 100,
      optimal_flow_min: 2000,
      optimal_flow_max: 5000,
      season: 'December-March',
      hazards: ['Massive holes', 'Huge waves', 'High consequence'],
      access_notes: 'Futaleufú, Chile. International destination.',
      permit_required: false,
    },
    {
      name: 'Terminator',
      river: 'Futaleufú River',
      description: 'Class V rapid with enormous hole known as the Terminator.',
      latitude: -43.1789,
      longitude: -71.8622,
      difficulty: 'V',
      length_miles: 0.1,
      gradient_fppm: 95,
      optimal_flow_min: 2000,
      optimal_flow_max: 5000,
      season: 'December-March',
      hazards: ['Terminator hole', 'Waves', 'Rocks'],
      access_notes: 'Futaleufú, Chile.',
      permit_required: false,
    },

    // Additional California - Cherry Creek
    {
      name: 'Mushroom',
      river: 'Cherry Creek (Tuolumne tributary)',
      description: 'Class V rapid with large undercut mushroom rock.',
      latitude: 37.9556,
      longitude: -119.9789,
      difficulty: 'V',
      length_miles: 0.1,
      gradient_fppm: 130,
      optimal_flow_min: 800,
      optimal_flow_max: 2000,
      season: 'April-June',
      hazards: ['Undercut mushroom rock', 'Powerful hydraulics', 'Pinning'],
      access_notes: 'Cherry Creek. Expert paddlers only.',
      permit_required: true,
    },

    // Additional Idaho - Salmon River (Main)
    {
      name: 'Big Mallard',
      river: 'Salmon River (Main)',
      description: 'Class IV rapid with large waves and holes.',
      latitude: 45.3478,
      longitude: -115.9267,
      difficulty: 'IV',
      length_miles: 0.2,
      gradient_fppm: 15,
      optimal_flow_min: 8000,
      optimal_flow_max: 25000,
      season: 'May-July',
      hazards: ['Big waves', 'Holes', 'Long swim'],
      access_notes: 'Main Salmon. Permit required for camping.',
      permit_required: true,
    },

    // Additional Oregon - Rogue River
    {
      name: 'Blossom Bar',
      river: 'Rogue River',
      description: 'Technical Class IV rapid requiring precise navigation through boulder garden.',
      latitude: 42.4378,
      longitude: -124.1511,
      difficulty: 'IV',
      length_miles: 0.15,
      gradient_fppm: 30,
      optimal_flow_min: 1200,
      optimal_flow_max: 5000,
      season: 'May-September',
      hazards: ['Boulder maze', 'Pinning', 'Multiple channels'],
      access_notes: 'Wild Rogue Wilderness. Permit required.',
      permit_required: true,
    },
    {
      name: 'Rainie Falls',
      river: 'Rogue River',
      description: 'Class V waterfall with portage option. Often run on left.',
      latitude: 42.6767,
      longitude: -123.6178,
      difficulty: 'V',
      length_miles: 0.05,
      gradient_fppm: 80,
      optimal_flow_min: 1200,
      optimal_flow_max: 4000,
      season: 'May-September',
      hazards: ['Waterfall', 'Rocks', 'Undercuts'],
      access_notes: 'Rogue River. Scout/portage on left.',
      permit_required: true,
    },

    // Additional Washington - Wenatchee River
    {
      name: 'Drunkards Drop',
      river: 'Wenatchee River',
      description: 'Class III+ rapid with large wave train.',
      latitude: 47.5411,
      longitude: -120.7178,
      difficulty: 'III+',
      length_miles: 0.15,
      gradient_fppm: 35,
      optimal_flow_min: 2000,
      optimal_flow_max: 8000,
      season: 'May-August',
      hazards: ['Large waves', 'Holes', 'Rocks'],
      access_notes: 'Tumwater Canyon. Popular commercial section.',
      permit_required: false,
    },

    // Additional North Carolina - Nantahala River
    {
      name: 'Nantahala Falls',
      river: 'Nantahala River',
      description: 'Class III rapid, busiest whitewater rapid in the US. Very popular commercial run.',
      latitude: 35.2744,
      longitude: -83.6867,
      difficulty: 'III',
      length_miles: 0.1,
      gradient_fppm: 25,
      optimal_flow_min: 800,
      optimal_flow_max: 1200,
      season: 'Year-round (dam controlled)',
      hazards: ['Ledge', 'Holes', 'Crowds'],
      access_notes: 'Nantahala Gorge. Extremely popular.',
      permit_required: false,
    },

    // Additional California - Kern River
    {
      name: 'Royal Flush',
      river: 'Kern River (Forks of the Kern)',
      description: 'Class V rapid with multiple drops and technical moves.',
      latitude: 36.0589,
      longitude: -118.4378,
      difficulty: 'V',
      length_miles: 0.2,
      gradient_fppm: 140,
      optimal_flow_min: 800,
      optimal_flow_max: 2000,
      season: 'May-June',
      hazards: ['Multiple drops', 'Sieves', 'Undercuts'],
      access_notes: 'Forks of the Kern. Expert paddlers only.',
      permit_required: false,
    },

    // Additional Montana - Alberton Gorge (Clark Fork)
    {
      name: 'Tumbleweed',
      river: 'Clark Fork River',
      description: 'Class IV rapid with large hole and wave train.',
      latitude: 47.0311,
      longitude: -114.4722,
      difficulty: 'IV',
      length_miles: 0.15,
      gradient_fppm: 40,
      optimal_flow_min: 5000,
      optimal_flow_max: 15000,
      season: 'May-June',
      hazards: ['Large hole', 'Waves', 'Rocks'],
      access_notes: 'Alberton Gorge. I-90 access.',
      permit_required: false,
    },

    // Additional West Virginia - Cheat River
    {
      name: 'Big Nasty',
      river: 'Cheat River',
      description: 'Class IV rapid with large wave train and holes.',
      latitude: 39.5667,
      longitude: -79.7733,
      difficulty: 'IV',
      length_miles: 0.2,
      gradient_fppm: 30,
      optimal_flow_min: 1500,
      optimal_flow_max: 8000,
      season: 'March-May',
      hazards: ['Big waves', 'Holes', 'Undercuts'],
      access_notes: 'Cheat Canyon. Popular springtime run.',
      permit_required: false,
    },
    {
      name: 'Coliseum',
      river: 'Cheat River',
      description: 'Class III-IV rapid with large waves at higher flows.',
      latitude: 39.5711,
      longitude: -79.7689,
      difficulty: 'III-IV',
      length_miles: 0.15,
      gradient_fppm: 28,
      optimal_flow_min: 2000,
      optimal_flow_max: 10000,
      season: 'March-May',
      hazards: ['Large waves', 'Holes', 'Rocks'],
      access_notes: 'Cheat Canyon.',
      permit_required: false,
    },

    // Additional Colorado - Gunnison River (Black Canyon)
    {
      name: 'S.O.B.',
      river: 'Gunnison River',
      description: 'Class V rapid in Black Canyon. Extremely difficult and remote.',
      latitude: 38.5767,
      longitude: -107.7211,
      difficulty: 'V',
      length_miles: 0.2,
      gradient_fppm: 90,
      optimal_flow_min: 800,
      optimal_flow_max: 2000,
      season: 'May-July',
      hazards: ['Massive boulders', 'Sieves', 'Remote location'],
      access_notes: 'Black Canyon. Extremely remote. Expert only.',
      permit_required: true,
    },

    // Additional Tennessee - Ocoee Upper
    {
      name: 'Tablesaw',
      river: 'Ocoee River (Upper)',
      description: 'Class IV rapid with sharp rocks and powerful hydraulics.',
      latitude: 35.0544,
      longitude: -84.5089,
      difficulty: 'IV',
      length_miles: 0.1,
      gradient_fppm: 60,
      optimal_flow_min: 600,
      optimal_flow_max: 1200,
      season: 'March-October (dam releases)',
      hazards: ['Sharp rocks', 'Holes', 'Undercuts'],
      access_notes: 'Upper Ocoee. Technical section.',
      permit_required: false,
    },

    // Additional Wyoming - Shoshone River
    {
      name: 'Clarks Fork Canyon',
      river: 'Clarks Fork Yellowstone River',
      description: 'Class V canyon rapid with big water and continuous action.',
      latitude: 45.0233,
      longitude: -109.3378,
      difficulty: 'V',
      length_miles: 0.3,
      gradient_fppm: 110,
      optimal_flow_min: 2000,
      optimal_flow_max: 5000,
      season: 'June-July',
      hazards: ['Continuous rapids', 'Big water', 'Remote canyon'],
      access_notes: 'Clarks Fork Canyon. Very remote.',
      permit_required: false,
    },

    // Additional Pennsylvania - Lehigh River
    {
      name: 'Triple Drop',
      river: 'Lehigh River',
      description: 'Class III rapid with three successive drops.',
      latitude: 40.9333,
      longitude: -75.6489,
      difficulty: 'III',
      length_miles: 0.1,
      gradient_fppm: 35,
      optimal_flow_min: 1200,
      optimal_flow_max: 4000,
      season: 'March-May (dam releases)',
      hazards: ['Three drops', 'Holes', 'Rocks'],
      access_notes: 'Lehigh Gorge. Dam controlled.',
      permit_required: false,
    },

    // Additional New Mexico - Rio Grande
    {
      name: 'The Box',
      river: 'Rio Grande',
      description: 'Class IV canyon section with continuous rapids.',
      latitude: 36.4678,
      longitude: -105.6411,
      difficulty: 'IV',
      length_miles: 0.5,
      gradient_fppm: 50,
      optimal_flow_min: 600,
      optimal_flow_max: 2000,
      season: 'May-June',
      hazards: ['Continuous rapids', 'Remote canyon', 'Cold water'],
      access_notes: 'Taos Box section. Popular multi-day.',
      permit_required: false,
    },
  ];

  try {
    let successCount = 0;
    let errorCount = 0;

    console.log(`\nAdding ${sampleRapids.length} rapids to database...\n`);

    for (const rapid of sampleRapids) {
      try {
        const result = await pool.query(
          `INSERT INTO rapids
           (name, river, description, location, difficulty, length_miles, gradient_fppm,
            optimal_flow_min, optimal_flow_max, season, hazards, access_notes, permit_required)
           VALUES ($1, $2, $3, ST_SetSRID(ST_MakePoint($4, $5), 4326)::geography, $6, $7, $8, $9, $10, $11, $12, $13, $14)
           ON CONFLICT DO NOTHING
           RETURNING id`,
          [
            rapid.name,
            rapid.river,
            rapid.description,
            rapid.longitude,
            rapid.latitude,
            rapid.difficulty,
            rapid.length_miles,
            rapid.gradient_fppm,
            rapid.optimal_flow_min,
            rapid.optimal_flow_max,
            rapid.season,
            rapid.hazards,
            rapid.access_notes,
            rapid.permit_required,
          ]
        );

        if (result.rows.length > 0) {
          successCount++;
          console.log(`✓ Added: ${rapid.name} (${rapid.river}) - Class ${rapid.difficulty}`);
        }
      } catch (err) {
        errorCount++;
        console.error(`✗ Failed to add ${rapid.name}:`, err.message);
      }
    }

    console.log(`\n🎉 Seeding complete!`);
    console.log(`   Success: ${successCount} rapids`);
    console.log(`   Errors: ${errorCount} rapids`);

    // Add some sample flow data for a subset of rapids
    console.log('\n💧 Adding sample flow data...');
    const rapidsResult = await pool.query('SELECT id FROM rapids LIMIT 20');

    for (const rapid of rapidsResult.rows) {
      await pool.query(
        `INSERT INTO flow_data (rapid_id, gauge_id, flow_cfs, gauge_height_ft, temperature_f, recorded_at)
         VALUES ($1, $2, $3, $4, $5, NOW())`,
        [
          rapid.id,
          'USGS-' + Math.floor(Math.random() * 100000),
          Math.floor(Math.random() * 8000) + 500,
          Math.random() * 8 + 1,
          Math.random() * 25 + 40,
        ]
      );
    }

    console.log('✓ Sample flow data added for 20 rapids');

  } catch (error) {
    console.error('❌ Error seeding data:', error);
    throw error;
  }
}

// Run if called directly
if (require.main === module) {
  seedSampleData()
    .then(() => {
      console.log('\n✓ Seeding completed successfully');
      process.exit(0);
    })
    .catch((error) => {
      console.error('\n✗ Seeding failed:', error);
      process.exit(1);
    });
}

module.exports = { seedSampleData };
